### ISSUE TITLE
Can't use out-of-box

### ISSUE THREAD

**Issue by yang** [benchling/coffeelint-forbidden-keywords#4]
When simply following the instructions and doing:

```
$ npm install --save coffeelint-forbidden-keywords
...

$ git diff
diff --git a/coffeelint.json b/coffeelint.json
index 2640c55..12c663f 100644
--- a/coffeelint.json
+++ b/coffeelint.json
@@ -123,5 +123,9 @@
     },
     "ensure_comprehensions": {
         "level": "ignore"
+    },
+    "forbidden_keywords": {
+        "module": "coffeelint-forbidden-keywords",
+        "level": "error"
     }
 }
```

I seem to get:

```
Error: Cannot find module 'coffeelint-forbidden-keywords' from '/home/yang/proj/wab/lib'
  at module.exports (/home/yang/proj/wab/node_modules/coffeelint/node_modules/resolve/lib/sync.js:33:11)
  at expandModuleNames (/home/yang/proj/wab/node_modules/coffeelint/lib/configfinder.js:78:35)
  at Object.exports.getConfig (/home/yang/proj/wab/node_modules/coffeelint/lib/configfinder.js:111:16)
  at getFallbackConfig (/home/yang/proj/wab/node_modules/coffeelint/lib/commandline.js:95:27)
  at lintFiles (/home/yang/proj/wab/node_modules/coffeelint/lib/commandline.js:69:38)
  at Object.<anonymous> (/home/yang/proj/wab/node_modules/coffeelint/lib/commandline.js:213:21)
  at Object.<anonymous> (/home/yang/proj/wab/node_modules/coffeelint/lib/commandline.js:218:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/yang/proj/wab/node_modules/coffeelint/bin/coffeelint:34:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

Is this because there's no index.js, only index.coffee?

**Comment by saifelse** [comment]
Interesting. I'm surprised that this error happens given that `commandline.js` runs `CoffeeScript.register();`... but in any case, I've added an `index.js` file in v0.1.1

**Comment by yang** [comment]
Thanks!
